@startuml
'https://plantuml.com/class-diagram


package model <<Frame>> {
  class i18n {
    + translatePage()
  }
  class i18next {
    + changeLanguage(lng, callback)
  }
  class Login {
    + Login()
    + logout()
    + getLoginStatus()
  }
  package exception <<Frame>> {
    class LoginException {
    }
    class UnauthorizedLoginException {
    }
    class UndefinedLoginException {
    }
    class UnknownLoginException {
    }
  }
}

i18n <--> i18next
package view <<Frame>> {
    class index {
    }
    class LoginForm {
    }
}
i18n --> index

package api <<Frame>> {
  class FacebookSDK{}
}
LoginException <|-- UnauthorizedLoginException 
LoginException <|-- UndefinedLoginException
LoginException <|-- UnknownLoginException
Login ..> UnauthorizedLoginException
Login ..> UndefinedLoginException
Login ..> UnknownLoginException
Login --> FacebookSDK
LoginForm <-- Login
@enduml