@startuml
'https://plantuml.com/class-diagram


package model <<Frame>> {
  class i18n {
    + translatePage()
  }
  class i18next {
    + changeLanguage(lng, callback)
  }
  class login {
    + login()
    + logout()
    + getLoginStatus()
  }
}

i18n <--> i18next
package view <<Frame>> {
    class index {
    }
}
i18n --> index

package exception <<Frame>> {
  class loginException {
  }
  class unauthorizedLoginException {
  }
@enduml